export enum ModuleNotification {
    CONFIG = "CONFIG",
    DATA = "DATA",
    ALL_MODULES_STARTED = "ALL_MODULES_STARTED",
    REQUEST_HISTORY = "REQUEST_HISTORY",
    HISTORY_DATA = "HISTORY_DATA"
}